=== BackupTheBerlios/lusi-svn/trunk/web-src/screenshotsList.dtd
<!ELEMENT ul (li*)>
<!ATTLIST ul id CDATA #FIXED "screenshotsList"
             xmlns CDATA #FIXED "http://www.w3.org/1999/xhtml">

<!ELEMENT li (p, a)>

<!ELEMENT p (#PCDATA)>

<!ELEMENT a (img)>
<!ATTLIST a href CDATA #REQUIRED
            title CDATA #REQUIRED>

<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA #IMPLIED
              alt CDATA #REQUIRED
              width CDATA #IMPLIED
              height CDATA #IMPLIED>

=== BackupTheBerlios/lusi-svn/trunk/web-src/screenshotsList.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE ul SYSTEM "screenshotsList.dtd">

<ul id="screenshotsList" xmlns="http://www.w3.org/1999/xhtml">
	<li>
		<p>[Mockup] Installer with hidden details</p>
		<a href="images/screenshots/MockupHiddenDetails.png" title="Click for full size">
			<img src="images/screenshots/MockupHiddenDetails-192.png" alt="Mockup, installer with hidden details" width="192" height="144"/>
		</a>
	</li>
	<li>
		<p>[Mockup] Installer with hidden documentation</p>
		<a href="images/screenshots/MockupHiddenDocumentation.png" title="Click for full size">
			<img src="images/screenshots/MockupHiddenDocumentation-192.png" alt="Mockup, installer with hidden documentation" width="192" height="144"/>
		</a>
	</li>
	<li>
		<p>[Mockup] Installer showing documentation and details</p>
		<a href="images/screenshots/MockupAllShown.png" title="Click for full size">
			<img src="images/screenshots/MockupAllShown-192.png" alt="Mockup, installer with all shown" width="192" height="144"/>
		</a>
	</li>
</ul>
